
package com.mysoap12;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorService1", targetNamespace = "http://MySOAP12.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CalculatorService1 {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://MySOAP12.com/CalculatorService1/getNumberRequest", output = "http://MySOAP12.com/CalculatorService1/getNumberResponse")
    public int getNumber();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://MySOAP12.com/CalculatorService1/iterateRequest", output = "http://MySOAP12.com/CalculatorService1/iterateResponse")
    public int iterate();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://MySOAP12.com/CalculatorService1/setZeroRequest", output = "http://MySOAP12.com/CalculatorService1/setZeroResponse")
    public String setZero();

}
